var data = [["God of War 4", "God of War 4", "Sony", "Many years have passed since Kratos took his vengeance against the Olympian gods, destroying the Greek world. Having survived his final encounter with Zeus, Kratos now lives with his young son Atreus in the world of the Norse gods, a savage land inhabited by many ferocious monsters and warriors. In order to teach his son how to survive in such a world, Kratos must master the rage that has driven him for many years and embrace his newfound role as a single father and mentor. Kratos must also contend with the Norse gods themselves as they are taking precautions against him, due to them being aware of his role in the destruction of Olympus. Over the course of their time together, Atreus learns more about his father's complicated and shady past, while struggling with the choice to follow in his father's footsteps, or choose his own path.", "59.99"],
			["Witcher 3", "Witcher 3", "CD Projekt", "The Witcher 3 is a story-driven, next-generation open world role-playing game, set in a visually stunning fantasy universe, full of meaningful choices and impactful consequences. You play as Geralt of Rivia, a monster hunter tasked with finding a child from an ancient prophecy. Geralt of Rivia, is a witcher, or monster hunter for hire, a white-haired and cat-eyed legend in his own time. Trained from early childhood and mutated to gain superhuman skills, strength and reflexes, witchers like Geralt are a natural consequence of and counterbalance to the monster-infested world in which they live. As Geralt, you'll embark on an epic journey in a war-ravaged world that will inevitably lead you to confront a foe darker than anything humanity has faced so far, the Wild Hunt.", "39.99"],
			["Horizon Zero Dawn", "Horizon Zero Dawn", "Sony", "The story is set in the 31st century, in a world where humans have regressed to primitive tribal societies as a result of some unspecified calamity. Their technologically advanced predecessors are vaguely remembered as the 'Old Ones.' Large robotic creatures known merely as 'machines' now dominate the Earth. For the most part, they peacefully coexist with humans, who occasionally hunt them for parts. However, a phenomenon known as the 'Derangement' has caused machines to become more aggressive towards humans, and larger and deadlier machines have begun to appear. There are three tribes that are prominently featured: the Nora, the Carja, and the Oseram. The Nora are fierce hunter-gatherers who live in the mountains and worship nature as the 'All-Mother.' The Carja are desert-dwelling city builders who worship the Sun. The Oseram are tinkerers known for their metalworking, brewing, and arguing.", "29.99"],
			["Bloodborne", "Bloodborne", "Sony", "Bloodborne takes place in Yharnam, a decrepit Gothic city known for its medical advances using blood as a primary tool. Over the years, many travelers journey to the city seeking the remedy to cure their afflictions; the player's character journeys to Yharnam seeking something known as Paleblood for reasons unknown. Upon arriving in the city, however, it is discovered that Yharnam is plagued with an endemic illness that has transformed most of its citizens into bestial creatures. The player must navigate the streets of Yharnam during the night of The Hunt, and overcome its violently deranged inhabitants and horrifying monsters in order to stop the source of the plague and escape the nightmare.", "19.99"],
			["Grand Theft Auto V", "Grand Theft Auto V", "Rockstar Games", "When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with some of the most frightening and deranged elements of the criminal underworld, the U.S. government and the entertainment industry, they must pull off a series of dangerous heists to survive in a ruthless city in which they can trust nobody, least of all each other.", "29.99"],
			["Overwatch", "Overwatch", "Blizzard Entertainment", "In a time of global crisis, an international task force of heroes banded together to restore peace to a war-torn world: OVERWATCH. It ended the crisis and helped to maintain peace in the decades that followed, inspiring an era of exploration, innovation, and discovery. But after many years, Overwatch's influence waned, and it was eventually disbanded. Overwatch is gone… but the world still needs heroes.", "39.99"],
			["Uncharted 4: A Thief's End", "Uncharted 4", "Sony", "Set three years after the events of UNCHARTED 3: Drake's Deception, Nathan Drake has presumably left the world of fortune hunting behind. However, it doesn't take long for adventure to come calling when Drake's brother, Sam, resurfaces seeking his help to save his own life and offering an adventure Drake can't resist. On the hunt for Captain Henry Avery's long-lost treasure, Sam and Drake set off to find Libertalia, the pirate utopia deep in the forests of Madagascar. UNCHARTED 4: A Thief's End takes players on a journey around the globe, through jungle isles, urban cities and snow-capped peaks on the search for Avery's fortune.", "29.99"],
			["Far Cry 5", "Far Cry 5", "Ubisoft", "The game is set in the fictional Hope County, Montana, where a preacher named Joseph Seed (portrayed by Greg Bryk) has risen to prominence. Seed believes that he has been chosen by God to protect the people of Hope County from an 'inevitable collapse' and has established a congregation called the Project at Eden's Gate. Ostensibly, this is to fulfill his mission of leading the people to salvation; in reality, Seed is a radical preacher and Eden's Gate is a militaristic doomsday cult. Under his rule, Eden's Gate has used both coercion and violence to forcibly convert the residents of Hope County, and intimidation to keep them from contacting the outside world for help. Seed has assumed the title of 'the Father' and maintains control over Hope County with the aid of the Heralds: Jacob, 'the Soldier' (Mark Pellegrino), a former military officer and Joseph's older brother who oversees the training and deployment of the cult's armed soldiers; John, 'the Baptist' (Seamus Dever), Joseph's younger brother and a lawyer who has been able to acquire much of the land in Hope County for Eden's Gate who leads the forcible conversion of residents; and Faith, 'the Siren' (Jenessa Grant), an early member of the cult who rose up and acts as a pacifist to bring the people to trust in Joseph, but runs forced labour camps for residents who resist the cult. The player takes on the role of a rookie sheriff's deputy referred to as 'the Deputy' who is part of a task force sent to arrest Seed. The residents of Hope County opposed to Seed include a cast of characters who join the fight with motives ranging from altruism to revenge, profit and boredom.", "59.99"],
			["Metal Gear Solid V: The Phantom Pain", "MGSV", "Konami", "Nine years after the events of MGSV: GROUND ZEROES and the fall of Mother Base, Snake a.k.a. Big Boss, awakens from a nine year coma. The year is 1984. The Cold War serves as the backdrop as nuclear weapons continue to shape a global crisis. Driven by revenge, Snake establishes a new private army and returns to the battlefield in pursuit of the shadow group, XOF.", "19.99"],
			["Destiny 2", "Destiny 2", "Activision", "Humanity's last safe city has fallen to an overwhelming invasion force, led by Ghaul, the imposing commander of the brutal Red Legion. He has stripped the city's Guardians of their power, and forced the survivors to flee. You will venture to mysterious, unexplored worlds of our solar system to discover an arsenal of weapons and devastating new combat abilities. To defeat the Red Legion and confront Ghaul, you must reunite humanity's scattered heroes, stand together, and fight back to reclaim our home.", "49.99"],
			["Assassin's Creed: Origins", "ACOrigins", "Ubisoft", "Ancient Egypt, a land of majesty and intrigue, is disappearing in a ruthless fight for power. Unveil dark secrets and forgotten myths as you go back to the one founding moment: The Origins of the Assassin's Brotherhood. Sail down the Nile, uncover the mysteries of the pyramids or fight your way against dangerous ancient factions and wild beasts as you explore this gigantic and unpredictable land. Engage into multiple quests and gripping stories as you cross paths with strong and memorable characters, from the wealthiest high-born to the most desperate outcasts. Experience a completely new way to fight. Loot and use dozens of weapons with different characteristics and rarities. Explore deep progression mechanics and challenge your skills against unique and powerful bosses.", "29.99"],
			["The Last of Us Remastered", "The Last of Us Remastered", "Sony", "The Last of Us takes place in the year 2033, twenty years after a fungal-based, brain-altering pandemic has spread and infected over 60% of the world's population. Since the outbreak, the world has gone into a state of panic and frenzy as officials try to fix and keep the situation under control. When the World Health Organization's attempts to procure a vaccine fail, the United States government does away with the bureaucrats in power and the establishment of civilian government. The country is turned into a police state under the control of homeland security and the military, and cities across the nation are placed under martial law one by one. Survivors of the pandemic are assigned to designated quarantine zones that are supposed to separate them from the infected and keep them safe.", "19.99"],
			["Dark Souls III", "Dark Souls III", "Bandai Namco", "Set in the Kingdom of Lothric, a bell has rung to signal that the First Flame, responsible for maintaining the Age of Fire, is dying out. As has happened many times before, the coming of the Age of Dark produces the undead, cursed beings that rise up after death. The Age of Fire can be prolonged with the linking of the fires, a ritual in which great lords and heroes sacrifice their souls to rekindle the First Flame. However, Prince Lothric, the chosen linker for this age, has abandoned his duty and instead chooses to watch the flame die from afar. The bell is the last hope for the Age of Fire, resurrecting previous Lords of Cinder (heroes who linked the flame in past ages) to attempt to link the fire again, but all but one Lord shirk their duty. The Ashen One, an Undead who failed to become a Lord of Cinder called an Unkindled, rises and must link the fire by returning Prince Lothric and the defiant Lords of Cinder to their thrones in the Firelink Shrine. The Lords include the Abyss Watchers, a legion of warriors sworn to protect the land from the Abyss and linked by a single soul; Yhorm the Giant, who was once a conqueror of the very people for whom he then sacrificed his life; and Saint Aldrich of the Deep, who became a Lord of Cinder despite his ravenous appetite for both men and gods. Lothric himself was raised in order to link the First Flame, but rejected his destiny, leaving the task to his elder brother Lorian, who was crippled and driven mad as a result of the ritual.", "19.99"],
			["Nier: Automata", "Nier", "Square Enix", "NieR: Automata is set centuries after the events of the original NieR. At the end of NieR, it was unclear whether Project Gestalt was a success or not, especially when you take that game's multiple endings into consideration. However, Automata tells us that aliens have invaded Earth, and because of this, the humans have been forced to take refuge on the moon. From this, we can infer that Project Gestalt must have been a success. To take back Earth from the machine lifeforms created by the aliens, the YoRHa androids were created. These elite androids are tasked with helping the android resistance force on Earth to battle against the machines. ", "49.99"],
			["Fallout 4", "Fallout 4", "Bethesda", "Fallout 4 takes place in the year 2287, ten years after the events of Fallout 3 and 210 years after the Great War, a war between the United States and China over natural resources that ended in a nuclear holocaust in 2077. The setting is a post-apocalyptic retro-future, covering a region that includes Boston, Massachusetts and other parts of New England known as 'The Commonwealth'. Unlike the previous titles, Fallout 4's story begins on the day the bombs dropped: October 23, 2077. The player's character (voiced by either Courtenay Taylor or Brian T. Delaney) takes shelter in Vault 111, emerging exactly 210 years later, on October 23, 2287. The game takes place in an alternate version of history that sees 1940s and 1950s aesthetics, design and technology advance in the directions imagined at the time. The resulting universe is thus a retro-futuristic one, where the technology has evolved enough to produce laser weapons, manipulate genes and create nearly-autonomous artificial intelligence, but all within the confines of 1950s solutions like the widespread use of atomic power and vacuum tubes, as well as having the integrated circuitry of the digital age. The architecture, advertisements and general living styles are also depicted to be largely unchanged since the 1950s, while including contemporary products, such as a robotic rocking horse for children in one advertisement, or posters for the underground vaults that play a central role in the storyline of the game.", "29.99"],
			["Star Wars Battlefront II", "Star Wars Battlefront II", "Electronic Arts", "Rush through waves of enemies on Starkiller Base with the power of your lightsaber in your hands. Storm through the jungle canopy of a hidden Rebel base on Yavin 4 with your fellow troopers, dispensing firepower from AT-STs. Line up your X-wing squadron for an attack on a mammoth First Order Star Destroyer in space. Or rise as a new Star Wars hero - Iden, an elite Imperial special forces soldier - and discover an emotional and gripping single-player story spanning thirty years. Experience rich and living Star Wars multiplayer battlegrounds across all three eras: prequel, classic, and new trilogy. Customize and upgrade your heroes, starfighters, or troopers, each with unique abilities to exploit in battle. Ride tauntauns or take control of tanks and speeders. Down Star Destroyers the size of cities, use the Force to prove your worth against iconic characters such as Kylo Ren, Darth Maul, or Han Solo, as you play a part in a gaming experience inspired by 40 years of timeless Star Wars films.", "59.99"],
			["Monster Hunter: World", "Monster Hunter", "Capcom", "Monster Hunter: World is an open-world action role-playing game played from a third-person perspective. Similar to previous games in the series, the player takes the role of a player-created character who travels to the 'New World', an unpopulated land mass filled with monsters, to join the Research Commission that study the land from their central command base of Astera. The Research Commission tasks the Hunter to hunt down and either kill or capture large monsters that roam outside Astera to both protect the Commission and to study the monsters there. The player's character does not have any intrinsic attributes, but instead these are determined by what equipment the character is equipped with. This includes a weapon, selected from the series' fourteen archetypes (such as long sword, bow, or hammer), which then further defines the types of combat moves and abilities the player can use, and pieces of armor, which can lead to beneficial or detrimental combat skills if matched properly. While some basic equipment can be purchased using in-game money, most equipment is built from loot obtained by slaying or trapping monsters, rewards from completing quests, or items gathered while in the field. This creates a core loop of gameplay that has the player fight monsters they can beat to obtain the right loot to craft improved weapons and armor to allow them to face more powerful monsters and the potential for even better equipment.", "59.99"]]

function getSyncScriptParams() {
         var scripts = document.getElementsByTagName('script');
         var lastScript = scripts[scripts.length-1];
         var scriptName = lastScript;
         return Number(scriptName.getAttribute('index'));
}

var index = getSyncScriptParams();

document.write('\
	<tr>\
		<td>\
			<div class="productPicture">\
				<a href="products/' + data[index][1] + '.html"><img src="assets/images/' + data[index][1] + '.jpg"></a>\
			</div>\
		</td>\
		<td>\
			<div class="productDetails">\
				<h1>' + data[index][0] + '</h1>\
				<h3>by ' + data[index][2] + '</h3>\
				<p>' + data[index][3] + '</p>\
			</div>\
		</td>\
		<td>\
			<div class="productPurchasing">\
				<h1>$' + data[index][4] + '</h1>\
				<input type="button" value="Buy Now!" onclick="window.location=\'products/' + data[index][1] + '.html\';">\
			</div>\
		</td>\
	</tr>\
	');